# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 09:12
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20191216_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
